###### NETWORK ######
MAINNET_RPC_PORT = 36304
TESTNET_RPC_PORT = 36305

OUTGOING_CONNECTIONS = 8
INCOMING_CONNECTIONS = 8

BOOTSTRAP_NODES = [] #list of ips form the bootstrap nodes
DNS_SEEDS = [] #list of ips from the dns seeds

###### STORAGE ######
LEVELDB_PATH = 'leveldb'
LEVELDB_CACHE_SIZE = 8 * (2 << 20)  # 8 MB
LEVELDB_WRITE_BUFFER_SIZE = 8 * (2 << 20)  # 8 MB
LEVELDB_BLOCK_SIZE = 2 * (2 << 10)  # 2 KB
LEVELDB_MAX_OPEN_FILES = 100
LEVELDB_BLOCK_CACHE_SIZE = 8 * (2 << 20)  # 8 MB
LEVELDB_COMPRESSION = False
LEVELDB_FILTER_BITS = 10

###### BLOCKCHAIN ######
TIME_PER_BLOCK = 30 # 30 seconds
DIFFICULTY_BLOCK_INTERVAL = 20 # 10 blocks (10 minutes)
DIFFICULTY_BLOCK_WINDOW = 10 # 10 blocks
DIFFICULTY_MAX_ADJUSTMENT_FACTOR = 4 
DIFFICULTY_MIN_ADJUSTMENT_FACTOR = 0.25

